import Head from 'next/head'
import BalanceCheckerCard from '@/components/BalanceCheckerCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dwelling Balance Checker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BalanceCheckerCard />
    </>
  )
}
